// Event Categories
export const EVENT_CATEGORIES = {
  TECH_PG: "Technical Event - pg ",
  TECH_UG: "Technical Event - ug",
  COMBINED: "Combined Technical Event – UG & PG",
  NON_TECH: "Non-Technical Event – UG & PG"
};

// All events with full details including icons and images
export const ALL_EVENTS = [
  // --- TECHNICAL PG ---
  {
    id: "code-kurukshetra",
    name: "Code Kurukshetra",
    category: EVENT_CATEGORIES.TECH_PG,
    subheading: "Coding & Debugging",
    icon: "⚔️",
    img: "/codekurukshetra.jpg",
    desc: "Code Kurukshetra is a high-intensity coding battlefield where participants face logical challenges, debugging rounds, and time-bound problem solving. This event tests algorithmic thinking and coding accuracy under pressure.",
    rules: [
     'Each team must consist of exactly 2 members.',
      'Participants must not use any electronic gadgets such as mobile phones, smartwatches, laptops, or any other smart devices during any round of the event.',
      'Participants are strictly prohibited from using or supporting any unfair means during the event.',
      'Any form of malpractice or rule violation observed at any stage will lead to immediate disqualification of the team.',
      'Participants must maintain discipline and decorum throughout the event.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
      'Participants are expected to have knowledge of one or more programming languages from the following: C, C++, Java, Python.',
      'Teams must adhere strictly to the time limits specified for each round to ensure the smooth flow of the event.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },
  {
    id: "web-astra",
    name: "Web Astra",
    category: EVENT_CATEGORIES.TECH_PG,
    subheading: "Web Development",
    icon: "🏹",
    img: "/webtech.jpg",
    desc: "A creative and technical challenge where participants showcase skills in UI/UX design and front-end development across two rounds.",
    rules: [
       'Each team must consist of exactly 2 members.',
      'The event will be conducted in two rounds.',
      'Round 1 focuses on UI/UX design using tools such as Figma or Canva.',
      'Round 2 involves web development based on the problem statement provided by the coordinators.',
      'Participants must not use any unauthorized electronic gadgets such as mobile phones, smartwatches, or personal laptops unless permitted by the event coordinators.',
      'Participants are strictly prohibited from copying designs, templates, or code from external sources or other teams.',
      'Any form of unfair means or malpractice will result in immediate disqualification.',
      'Teams must strictly adhere to the time limits specified for each round to ensure smooth conduct of the event.',
      'The decision of the judges and event coordinators shall be final and binding.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },
  {
    id: "brahma-bits",
    name: "Brahma Bits",
    category: EVENT_CATEGORIES.TECH_PG,
    subheading: "IT Quiz",
    icon: "🕉️",
    img: "/quiz.jpg",
    desc: "A knowledge-driven quiz designed to test understanding of core CS concepts, emerging technologies, and general IT awareness.",
    rules: [
      'Each team must consist of exactly 2 members.',
      'The event will be conducted in multiple rounds, with elimination at each stage based on performance.',
      'The quiz may include technical questions, logical reasoning, rapid-fire rounds, and visual or audio-based questions.',
      'Participants must not use any electronic gadgets such as mobile phones, smartwatches, laptops, or any reference materials during the event.',
      'Participants are strictly prohibited from using or supporting any unfair means at any stage of the quiz.',
      'Any form of malpractice or misbehavior will lead to immediate disqualification of the team.',
      'Teams must answer within the time limits specified for each round.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },
  {
    id: "data-vishleshana",
    name: "Data Vishleshana",
    category: EVENT_CATEGORIES.TECH_PG,
    subheading: "Data Sprint",
    icon: "📊",
    img: "/data.jpg",
    desc: "Transform raw datasets into meaningful insights and visual interpretations using Python and basic machine learning techniques.",
    rules: [
     'Each team must consist of exactly 2 members.',
      'Participants should have a basic understanding of Python programming and Jupyter Notebook.',
      'The dataset and problem statement will be provided by the event coordinators at the start of the event.',
      'Participants are expected to perform data cleaning, analysis, and visualization within the given time.',
      'Use of external datasets or pre-trained models and AI Tools is strictly prohibited.',
      'Participants must not use unauthorized electronic gadgets or any unfair means during the event.',
      'Any form of malpractice or rule violation will lead to immediate disqualification.',
      'Teams must strictly adhere to the time limits specified for the event.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },

  // --- TECHNICAL UG ---
  {
    id: "gandhari-mode",
    name: "Gandhari Mode",
    category: EVENT_CATEGORIES.TECH_UG,
    subheading: "Blind Coding",
    icon: "👁️‍🗨️",
    img: "/assets/blind_bg.jpg",
    desc: "A unique challenge where participants write code without seeing the screen, relying entirely on logic, syntax knowledge, and memory.",
    rules: [
      'Each team must consist of exactly 2 members.',
      'The event will be conducted in multiple rounds, with elimination based on performance in each round.',
      'Participants must write code without viewing the screen during the coding process.',
      'Accuracy of the code will be given more importance than execution speed.',
      'Participants must not use any electronic gadgets such as mobile phones, smartwatches, or reference materials during the event.',
      'Any form of unfair means or external assistance or Physical writing of code on paper will lead to immediate disqualification.',
      'Participants must strictly adhere to the time limits specified for each round.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },
  {
    id: "shilpa-chakra",
    name: "Shilpa Chakra",
    category: EVENT_CATEGORIES.TECH_UG,
    subheading: "Web Designing",
    icon: "☸️",
    img: "/assets/arch_bg.jpg",
    desc: "A creative battle building visually appealing web pages using HTML and CSS, evaluated on structure, creativity, and responsiveness.",
    rules: [
      'Each team must consist of exactly 2 members.',
      'The event will be conducted in two rounds, with evaluation after each round.',
      'Participants are required to have knowledge of basic HTML and CSS for designing the web pages.',
      'Use of AI tools, Pre written codes and Templets are strictly prohibited.',
      'Designs will be evaluated by judges based on creativity, layout, styling, and completeness.',
      'Participants must not use unauthorized electronic gadgets or external resources during the event.',
      'Any form of unfair means or malpractice will lead to immediate disqualification.',
      'Teams must strictly adhere to the time limits specified for each round.',
      'The decision of the judges and event coordinators shall be final and binding.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },
  {
    id: "bits-vedha",
    name: "Bits Vedha",
    category: EVENT_CATEGORIES.TECH_UG,
    subheading: "IT Quiz",
    icon: "📖",
    img: "/bits_vedha.jpg",
    desc: "Evaluates knowledge of core computer concepts, current tech trends, and recent developments in the industry.",
    rules: [
        'Each team must consist of exactly 2 members.',
      'The event will be conducted in multiple rounds, with elimination at each stage based on performance.',
      'The quiz may include questions related to computer fundamentals, programming concepts, current technology trends, and IT-related current affairs.',
      'Participants must not use any electronic gadgets such as mobile phones, smartwatches, laptops, or reference materials during the event.',
      'Participants are strictly prohibited from using or supporting any unfair means during the quiz.',
      'Any form of malpractice or misbehaviour will lead to immediate disqualification.',
      'Teams must answer within the time limits specified for each round.',
      'In case of any disputes or clarifications, participants should approach the quiz master or event coordinators politely and peacefully.',
      'The decision of the quiz master and Event Coordinators shall be final and binding.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },
  {
    id: "maya-loop",
    name: "Maya Loop",
    category: EVENT_CATEGORIES.TECH_UG,
    subheading: "Tech Illusion",
    icon: "🌀",
    img: "/assets/logic_bg.jpg",
    desc: "A mind-bending event challenging observation, logic, and awareness. Things may not be what they seem!",
    rules: [
      'Each team may consist of 1 or 2 members.',
      'The event will be conducted in multiple rounds, details of which will be revealed during the event.',
      'Participants must rely on observation, logic, and quick thinking to progress through the rounds.',
      'Use of mobile phones or any electronic gadgets is strictly prohibited unless permitted by the event coordinators.',
      'Any form of unfair means or malpractice will result in immediate disqualification.',
      'Participants must strictly adhere to the time limits specified for each round.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
      'The decision Event coordinators shall be final and binding.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },

  // --- COMBINED ---
  {
    id: "shastrartha-vada",
    name: "Shastrartha Vāda",
    category: EVENT_CATEGORIES.COMBINED,
    subheading: "IT Debate",
    icon: "🗣️",
    img: "/debate.jpg",
    desc: "A competitive debate on contemporary IT topics, emerging technologies, and digital trends in a versus-against format.",
    rules: [
       'Each team must consist of exactly 2 members.',
      'The event will be conducted in multiple rounds with versus-against debate formats.',
      'Debate topics will be related to information technology, emerging technologies, and digital trends.',
      'Participants will be evaluated by judges based on communication skills, clarity of thought, confidence, and validity of points presented.',
      'Use of mobile phones or any electronic gadgets during the debate is strictly prohibited.',
      'Participants must maintain professional conduct, discipline, and respect towards opponents and judges.',
      'Any form of misbehavior or unfair practice will lead to immediate disqualification.',
      'Participants must strictly adhere to the time limits assigned for each round.',
      'The decision of the judges and event coordinators shall be final and binding.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  },

  // --- NON TECHNICAL ---
  {
    id: "ranabhoomi-arena",
    name: "Ranabhoomi Arena",
    category: EVENT_CATEGORIES.NON_TECH,
    subheading: "Mobile Gaming (BGMI)",
    icon: "🎮",
    img: "/assets/gaming_bg.jpg",
    desc: "A competitive virtual battlefield emphasizing teamwork, strategy, and coordination.",
    rules: [
      'Each team must consist of exactly 4 members.',
      'No cheating, exploiting bugs, or foul play is allowed. Any violation will result in immediate disqualification.',
      'Use of any unfair means, hacks, modded applications, or emulators is strictly prohibited.',
      'Players must bring all necessary accessories such as chargers, headphones, power banks, etc.',
      'Players are required to download all maps and required resource packs in advance to ensure smooth gameplay during the event.',
      'Wi-Fi will not be provided by the college. Participants must use their own mobile data or internet connection for the game.',
      'Participants must maintain discipline and sportsmanship throughout the event.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
    ],
    fees: "₹400 per team",
    regLink: "#"
  },
  {
    id: "bids-sabha",
    name: "Bids Sabha",
    category: EVENT_CATEGORIES.NON_TECH,
    subheading: "IPL Auction",
    icon: "🔨",
    img: "/auction.jpg",
    desc: "Act as team owners and build a dream cricket team within a fixed virtual budget.",
    rules: [
       'Each team must consist of the 4 Participants.',
      'The event will be conducted in auction-based rounds, following standard IPL auction rules.',
      'Each team will be provided with a fixed virtual budget to bid for players.',
      'Teams must carefully plan their bids to form a balanced and competitive team.',
      'Any form of unfair means, external assistance, or rule manipulation will result in immediate disqualification.',
      'Participants must maintain discipline and sportsmanship throughout the event.',
      'Teams must strictly adhere to the auction rules and time limits set for bidding.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
      'The decision of the event coordinators shall be final and binding.',
    ],
    fees: "₹500 per team",
    regLink: "#"
  },
  {
    id: "nidhi-404",
    name: "Nidhi 404",
    category: EVENT_CATEGORIES.NON_TECH,
    subheading: "Treasure Hunt",
    icon: "💎",
    img: "/assets/hunt_bg.jpg",
    desc: "Solve clues, decode hints, and navigate checkpoints to uncover hidden treasure.",
    rules: [
    'Each team must consist of the 4 - 5 members.',
      'The event will be conducted in multiple rounds, with progressive elimination based on clue-solving accuracy and completion time.',
      'Clues may include logical puzzles, riddles, technical hints, and location-based challenges.',
      'Participants must not use any unfair means or external assistance during the event.',
      'Use of mobile phones or electronic gadgets is prohibited unless explicitly permitted by the event coordinators.',
      'Teams must strictly adhere to the rules and time limits specified for each round.',
      'Any form of misbehaviour, rule violation, or malpractice will lead to immediate disqualification.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
    ],
    fees: "₹500 per team",
    regLink: "#"
  },
  {
    id: "drishti-pov",
    name: "Drishti POV",
    category: EVENT_CATEGORIES.NON_TECH,
    subheading: "Mobile Photography",
    icon: "📸",
    img: "/assets/photo_bg.jpg",
    desc: "Focus on perspective, creativity, and storytelling through images captured strictly via mobile phones.",
    rules: [
      'Participation may be individual.',
      'Participants are allowed to use only mobile phones for capturing photographs.',
      'Use of DSLRs, mirrorless cameras, or any professional photography equipment is strictly prohibited.',
      'Photographs must be captured during the event and not sourced from the gallery or external platforms.',
      'Editing or use of filters is not allowed unless explicitly permitted by the event coordinators.',
      'Photographs will be evaluated by judges based on creativity, composition, theme relevance, and clarity.',
      'Any form of plagiarism or unfair means will lead to immediate disqualification.',
      'Participants must strictly adhere to the time limits and rules specified for the event.',
      'The decision of the judges and event coordinators shall be final and binding.',
    ],
    fees: "₹250 per participant",
    regLink: "#"
  },
  {
    id: "rahasya-mintz",
    name: "Rahasya Mintz",
    category: EVENT_CATEGORIES.NON_TECH,
    subheading: "Surprise Event",
    icon: "❓",
    img: "/mystery.jpg",
    desc: "A fun-filled surprise event with unexpected twists. Details revealed only at the venue.",
    rules: [
      'Each team must consist of exactly 2 participants.',
      'No details or clues about the event will be disclosed prior to the event.',
      'Once registered, participants are not allowed to back out of the event.',
      'The event is purely fun-oriented and non-technical.',
      'Participants must follow the instructions given by the event coordinators during the event.',
      'Any form of misbehaviour or unfair means will lead to immediate disqualification.',
      'Participants must maintain discipline and sportsmanship throughout the event.',
      'In case of any disputes or clarifications, participants should approach the event coordinators politely and peacefully.',
      'The decision of the event coordinators shall be final and binding.',
    ],
    fees: "₹250 per team",
    regLink: "#"
  }
];

export const SECTIONS = [
  {
    video: "/videos/warrwarr0.webm",
    title: "Technical Events – PG",
    events: [
      { name: "CODE KURUKSHETRA", desc: "Coding & Debugging" },
      { name: "WEB ASTRA", desc: "Web Development" },
      { name: "BRAHMA BITS", desc: "IT Quiz" },
      { name: "DATA VISHLESHANA", desc: "Data Sprint" },
    ],
  },
  {
    video: "/videos/draupadi2.webm",
    title: "Technical Events – UG",
    events: [
      { name: "GANDHARI MODE", desc: "Blind Coding" },
      { name: "SHILPA CHAKRA", desc: "Web Design" },
      { name: "BITS VEDHA", desc: "IT Quiz" },
      { name: "MAYA LOOP", desc: "Tech Illusion" },
    ],
  },
  {
    video: "/videos/bhishmaputra1.webm",
    title: "Cultural & Non-Tech",
    events: [
      { name: "SHASTRARTHA VĀDA", desc: "IT DEBATE  " },
      { name: "RANABHOOMI ARENA", desc: "BGMI Gaming" },
      { name: "DRISHTI POV", desc: "Photography" },
      { name: "BIDS SABHA", desc: "IPL Auction" },
      { name: "NIDHI 404", desc: "Treasure Hunt" },
      { name: "RAHASYA MINTZ", desc: "Surprise Event" },
    ],
  },
];
